version: '3.1'

services:
  nuxt:
    build: .
    tty: true
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - 8000:3000
    links:
      - wordpress

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 5000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    # Keep your data
    volumes:
      - ./wordpress:/var/www/html/
    # sub directory only
    # working_dir: /var/www/html/wp/

  cli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    # Keep your data
    volumes:
      - ./db:/var/lib/mysql
